### ISSUE TITLE
Syntax for powerplatform_rest (Resource) to link VNet Enterprise policy to a PowerApp environment

### ISSUE THREAD

**Issue by webstean** [microsoft/power-platform-terraform-quickstarts#125]
## Description

Microsoft provides a Powershell script to link an VNET PowerApp Enterprise Policy to PowerApp environment, is it possible to have someone smarter than me convert this a powerplatform_rest call in Terraform using this provider?

Might also be a good test case, to ensure powerplatform_rest (Resource) has all the necessary capabilities to do this sort of thing.

[Create Link Power Apps Enterprise Policy to an environment](https://github.com/microsoft/PowerApps-Samples/tree/master/powershell/enterprisePolicies#7-set-subnet-injection-for-an-environment)

## Definition of Done

- [ X] Link Enterprise Policy to PowerApp Environment for VNets

## Contributions

Do you plan to raise a PR to address this issue? NO

See the [contributing guide](/CONTRIBUTING.md?) for more information about what's expected for contributions.

**Comment by pawel-szon** [comment]
Hey @webstean, here is the code I'm running:


```hcl
resource "powerplatform_rest" "nonprod_iq8_link_enterprise_policy" {
  create = {
    scope                = "https://api.bap.microsoft.com/.default"
    url                  = "https://api.bap.microsoft.com/providers/Microsoft.BusinessAppPlatform/environments/${local.environment_id}/enterprisePolicies/NetworkInjection/link?&api-version=2019-10-01"
    method               = "POST"
    body                 = "{ 'SystemId' : '${local.enterprise_policy_systemId}'}"
    expected_http_status = [202]
  }

``` 

I hope this helps.

**Comment by mawasile** [comment]
powerplatform_enterprise_policy is now added to main branch and will be released asap
https://github.com/microsoft/terraform-provider-power-platform/commit/8385f36e46c484dd2a96c3838553519e4a853834

https://github.com/microsoft/terraform-provider-power-platform/tree/main/examples/resources/powerplatform_enterprise_policy
